apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-b5qs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-b5qs
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-b5qs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-b5qs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-b5qs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cznq-tenant/rhtap-demo-app/hacbs-test-project-b5qs@sha256:ee6c7d29a6274d2a183bf554f3e48ab63451b8b885b02df3249db22d483be68b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
